api:
  host: https://api.u-ride.app
  path: /otp/routers/default
  port: 
  v2: false 
branding: savvycommuter_logo
title: "Savvy Commuter"

# Support OTP-2 in parallel for certain requests
# api_v2:
#  host: http://localhost
#  path: /otp/routers/default
#  port: 8002

# Add suggested locations to be shown as options in the form view.
# locations:
#   - id: 'airport'
#     icon: 'plane'
#     name: 'Portland International Airport (PDX)'
#     lat: 45.587579
#     lon: -122.593084
#   - id: 'zoo'
#     icon: building
#     lat: 45.51010444232195
#     lon: -122.71607145667079
#     name: Oregon Zoo, Portland, OR

### Define the strategies for how to handle auto-planning of a new trip when
### different query parameters are changes in the form. The default config is
### shown below, but if autoPlan is set to false, auto-plan will never occur.
### Other strategies besides those shown below are: ANY (any changed param will
### cause a re-plan).
# autoPlan:
#   mobile: BOTH_LOCATIONS_CHANGED
#   default: ONE_LOCATION_CHANGED

### The default query parameters can be overridden be uncommenting this object.
### Note: the override values must be valid values within otp-ui's query-params.js
# defaultQueryParams:
#   maxWalkDistance: 3219 # 2 miles in meters

### The persistence setting is used to enable the storage of places (home, work),
### recent searches/places, user overrides, and favorite stops.
### Pick the strategy that best suits your needs.
###
### If you do not require remote storage of preferences,
### then use the localStorage strategy outlined below (which is used by default).
### The localStorage strategy will use the browser application storage.
### It must be enabled to show the stored locations (see above).
persistence:
  enabled: true
  strategy: localStorage
  ### This variable hides the "more info" link when accepting the terms of storage.
  ### If no terms of storage page content is set, this removes an otherwise dead link
  ### False is default in that if the value isn't set, the link isn't shown
  # terms_of_storage: true
  
### If using the OTP Middleware to store user profiles
### with Auth0 as the authentication mechanism,
### then use the otp_middleware strategy below instead:
# persistence:
#  enabled: true
#  strategy: otp_middleware
#  auth0:
#    domain: dev-ykbgf3g8ufkdbsz1
#    clientId: your-auth0-client-id
#  otp_middleware:
#    apiBaseUrl: https://otp-middleware.example.com
#    apiKey: your-middleware-api-key

### Adding additional menu items to the main menu items. Use the separator flag
### to include a separator line if you have groups of menu items
### If a Top level menu item contains submenu items (children) then use the 'children' flag.
### Icon URL is preferable over iconType. If none are given then a 'bus' iconType is used.
#App menu
extraMenuItems:
 - id: link-list
   label: Links
   iconType: 'link'
   iconUrl: ''
   children:
     - id: bus-website
       label: Savvy Commuter
       iconType: 'train'
       iconUrl: ''
       href: 'https://savvycommuter.org/otpexplore.html'
       separator: 'true'
     - id: car-website
       label: Contact Us
       iconType: 'send'
       iconUrl: ''
       href: 'https://savvycommuter.org/contact.html'

map:
  initLat: 26.31
  initLon: -80.05
  baseLayers:
    - name: Streets
      url: //cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png
      subdomains: "abcd"
      attribution: 'Map tiles: &copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>, &copy; <a href="https://carto.com/attributions">CARTO</a>'
      maxZoom: 20
      hasRetinaSupport: true
    - name: Stamen Toner Lite
      url: http://tile.stamen.com/toner-lite/{z}/{x}/{y}.png
      attribution: 'Map tiles by <a href="http://stamen.com">Stamen Design</a>, under <a href="http://creativecommons.org/licenses/by/3.0">CC BY 3.0</a>. Data by <a href="http://openstreetmap.org">OpenStreetMap</a>, under <a href="http://www.openstreetmap.org/copyright">ODbL</a>.'
  


# it is possible to leave out a geocoder config entirely. In that case only
# GPS coordinates will be used when finding the origin/destination.



# Use this mode config for the enhanced Transit+ config
modes:
  transitModes:
    - mode: BUS
      label: Bus
      # A mode color can be added, used throughout the application,
      # most notably in the enhanced stop viewer bubble
      color: blue
    - mode: TRAM
      label: MAX & Streetcar
    - mode: RAIL
      label: WES
    - mode: GONDOLA
      label: Aerial Tram

  accessModes:
    - mode: BICYCLE
      label: Transit + Bike

  bicycleModes:
    - mode: BICYCLE
      label: Own Bike
      iconWidth: 18


routingTypes:
  - key: ITINERARY
    text: Exact Time
    

# Itinerary options
itinerary:
  # Show fares for each transit leg (false if omitted).
  # (Requires using LineItinerary.)
  showRouteFares: false
  # Whether the plan first/previous/next/last buttons should be shown along with
  # plan trip itineraries.
  showPlanFirstLastButtons: false
  
  # If multiple fares are returned by OTP, assign names to the fare keys here
  #fareKeyNameMap:
  #  regular: "Transit Fare"
  #  electronicRegular: "SmartCard Fare"
  #  student: "Student Fare"
  # One fare will always be shown by default
  #defaultFareKey: electronicRegular

# The transitOperators key is a list of transit operators that can be used to
# order transit agencies when sorting by route. Also, this can optionally
# provide operator logos that appear in the the route viewer and itineraries).
# Note: these logos will override the values found in
# agency.txt#agency_branding_url.
#
# When sorting routes, otp-react-redux uses otp-ui's route-comparator which uses
# multiple criteria to sort routes. (See https://git.io/Jk2Ia). The routes are
# first sorted according to a comparator value based off of the agency. After
# sorting routes by the agency, additional sorting criteria is used for routes
# that yield the same agency comparator value.
#
# If the transitOperators key is not defined, route sorting will fall back to
# using the agency name. If the transitOperators key is defined, the order field
# defined for each agency is used as a comparator value. Agencies are matched
# according to both the feedId and agencyId. If no match is found or the order
# field is not undefined, the associated routes will be placed after all other
# agencies which did have a match with a defined order value.
#
# This works best with the IBI fork of OTP which returns the necessary
# information in the route index API. Check the build logs of OTP to see what
# feedIds and agencyIds were found as these IDs can sometimes be auto-generated.
#
# Shown below is an example transitOperators config setting for the Portland, OR
# area which uses 2 GTFS files (from TriMet and C-TRAN).
#
# transitOperators:
#   - feedId: TriMet
#     agencyId: PSC
#     logo: https://d2tyb7byn1fef9.cloudfront.net/psc.png
#     order: 1
#   - feedId: TriMet
#     agencyId: TRIMET
#     name: TriMet
#     logo: http://news.trimet.org/wordpress/wp-content/uploads/2019/04/TriMet-logo-300x300.png
#     order: 1
#   - feedId: TriMet
#     agencyId: TRAM
#     logo: https://d2tyb7byn1fef9.cloudfront.net/tram.png
#     order: 1
#     # The C-TRAN GTFS feed does not come with feed_id or agency_id filled. The
#     # value of '1' is a feed_id and agency_id that OTP auto-generated.
#   - feedId: '1'
#     agencyId: '1'
#     name: C-TRAN
#     logo: https://d2tyb7byn1fef9.cloudfront.net/ctran.png
#     defaultRouteColor: ffffff
#     defaultRouteTextColor: '000000'
#     longNameSplitter: ' - '
#     order: 2
# Use this config to overwrite the accessibility score gradation
# map that ships with otp-ui
#accessibilityScore:
#    gradationMap:
#        0.0:
#            color: "#ffb5b9"
#            # The text can be overridden in the language section
#            text: 'Not Accessible'
#            icon: thumbs-down

### Use this config for the standard mode selector
# modeGroups:
#   - name: Transit
#     modes:
#       - TRAM
#       - BUS
#   - name: Walk/Bike
#     modes:
#       - WALK
#       - BICYCLE

### Language section to override strings.
### Strings can be set globally for all languages (e.g. for strings that are brands/nouns,
### e.g. TriMet's "TransitTracker") or by language.
### The nested structure should be the same as the language files under the i18n folder.
### You can also customize OTP error messages for itinerary searches based on OTP HTTP codes.
### A separate message can be set for each language or locale if necessary.
# language:
#   allLanguages
#     common:
#       accessModes:
#         bikeshare: Relay Bike
#   en-US:
#     common:
#       accessModes:
#         bikeshare: Blue Bike
#     config:
#       flex:
#         flex-service: Flex Service
#         call-ahead: "Call to reserve: (555) 555-5555"
#         continuous-dropoff: Communicate with operator about stop
#       acessibilityScore:
#         gradationMap:
#           0.0: 'Not Accessible'
#           0.9: 'Mostly Accessible'
#       menuItems:
#         demo-item: Demo Item
#     errorMessages:
#       404:
#         msg: Sorry, we couldn't find any transit or rideshare/carshare options at the time and/or location you chose. Please try again later, or change the settings of your trip.
#         # OTP modes in a string to be extracted (Format: [MODE1], [MODE2] (space included))
#         modes: "CAR_HAIL, CAR_RENT"
#       480:
#         msg: No available transit routes or rideshare/carshare service at origin.

### Localization section to provide language/locale settings
#localization:
#  # An ambient currency should be defined here (defaults to USD).
#  # In some components such as DefaultItinerary, we display a cost element
#  # that falls back to $0.00 (or its equivalent in the configured ambient currency
#  # and in the user-selected locale) if no fare or currency info is available.
#  currency: 'USD'
#  defaultLocale: 'en-US'

### If using OTP Middleware, you can define the optional phone number options below.
# phoneFormatOptions:
#  # ISO 2-letter country code for phone number formats (defaults to 'US')
#  countryCode: US

# set this value to change the absolute number of seconds of deviation from the
# schedule for a transit stop time to be considered early, on-time or late. The
# default is 60 seconds.
# onTimeThresholdSeconds: 60

# Format the date time format for display.
dateTime:
  longDateFormat: DD-MM-YYYY
# stopViewer:
#   # The radius (in meters) to use when searching for nearby stops and other
#   # amenities (rental vehicles, park and rides) to show for the focused stop.
#   nearbyRadius: 250
#   # The max. number of departures to show for each trip pattern
#   # in the stop viewer Next Arrivals mode
#   # (defaults to 3 if unspecified).
#   numberOfDepartures: 3
#   # Whether to display block IDs with each departure in the schedule mode.
#   # (defaults to false if unspecified).
#   showBlockIds: false
#   # Specifies the time window, in seconds, in which to search for next arrivals,
#   # so that, for example, if it is Friday and a route does
#   # not begin service again until Monday, we are showing its next
#   # departure and it is not entirely excluded from display
#   # (defaults to 4 days/345600s if unspecified).
#   timeRange: 345600
